### ISSUE TITLE
Error:(63, 119) error: incompatible types: Object cannot be converted to String

### ISSUE THREAD

**Issue by MarcinOrlowski** [johncarl81/parceler#293]
Hi,

Parceler was working fine here for a long time, yet recently I started to face 

    Error:(63, 119) error: incompatible types: Object cannot be converted to String

trying to compile generated code with recent Android Studio and build tools.

It complains about `write()` implementation, pointing at the `for` loop:

    public static void write(...Model domain$$1, android.os.Parcel parcel$$1, int flags$$0, IdentityCollection identityMap$$0) {
        int identity$$0 = identityMap$$0 .getKey(domain$$1);
        if (identity$$0 != -1) {
            parcel$$1 .writeInt(identity$$0);
        } else {
        	  [...]
            if (...BaseModel$$PackageHelper.accessBaseModel$FG$mTags(domain$$1) == null) {
                parcel$$1 .writeInt(-1);
            } else {
                parcel$$1 .writeInt(...BaseModel$$PackageHelper.accessBaseModel$FG$mTags(domain$$1).size());

                // compiler complains about the line below, IDE underlines `java.lang.String string$$0`
                for (java.lang.String string$$0 : ...BaseModel$$PackageHelper.accessBaseModel$FG$mTags(domain$$1)) {
                    parcel$$1 .writeString(string$$0);
                }
            }
            [...]
        }
    }

IDE underlines `java.lang.String string$$0` of the following line:

    for (java.lang.String string$$0 : ...BaseModel$$PackageHelper.accessBaseModel$FG$mTags(domain$$1)) {

Versions:

-  buildToolsVersion '25.0.3'
- Android Studio 3.0 Canary 3
- parceler: 1.1.8
- com.android.tools.build:gradle:3.0.0-alpha3

And in fact `mTags` is `ArrayList`.

**Comment by MarcinOrlowski** [comment]
To make it work again, I had to downgrade to 1.1.6 and add

    defaultConfig {

        ...

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath = true
            }
        }
    }

to my `build.gradle` file.

**Comment by johncarl81** [comment]
We just fixed this [here](https://github.com/johncarl81/parceler/pull/287), will be released in the upcoming 1.1.9 release.

**Comment by johncarl81** [comment]
Just released 1.1.9 with the fix. Let me know if this is still an issue.

**Comment by MarcinOrlowski** [comment]
I updated the project to use 1.1.9 but it makes no difference here. I still face
`Error:(63, 119) error: incompatible types: Object cannot be converted to String`

**Comment by johncarl81** [comment]
Can you share a simple reproducing case?

**Comment by mityai2002** [comment]
It is easy to reproduce. Let's say you have a class Parent residing in one package
`
package com.example.parceler.shared;

import org.parceler.Parcel;
import java.util.List;

@Parcel
public class Parent {
    List<Item> items;
}
`

And another class derived from it sitting in a different package:
`
@Parcel
public class Child extends Parent {
}
`
This causes error: incompatible types: Object cannot be converted to Item

**Comment by johncarl81** [comment]
Is `Item` is also a `@Parcel` annotated class?

**Comment by mityai2002** [comment]
Yes, updated the example.

**Comment by johncarl81** [comment]
Ah, there's a bug in the package helper code generation.  Thanks for pointing this out.

For the time being, you can make the field public to avoid the issue.

**Comment by johncarl81** [comment]
This is fixed but unreleased.  If you want to give 1.1.10-SNAPSHOT a try, let me know that it fixes your issue.

**Comment by MarcinOrlowski** [comment]
Why is it unreleased? I pretty much doubt it's that unique issue and currently 1.1.9 is pretty much useless?

**Comment by johncarl81** [comment]
Thought this was a corner case... have you given it a try?  Does it solve your prblem @MarcinMoskala ?

**Comment by MarcinOrlowski** [comment]
what repository 1.1.10-SNAPSHOT needs to be added to gradle file? 1.1.10-SNAPSHOT is not on sonatype

**Comment by johncarl81** [comment]
Maven central for snapshots: https://oss.sonatype.org/content/repositories/snapshots/
You can see the artifacts here: https://oss.sonatype.org/content/repositories/snapshots/org/parceler/parceler/1.1.10-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/parceler/parceler-api/1.1.10-SNAPSHOT/

**Comment by MarcinOrlowski** [comment]
ok, once you uploaded, 1.1.10-snapshot is now availble. My project builds with it now.

**Comment by DSteve595** [comment]
@johncarl81 I'm still seeing this in 1.1.7 through 1.1.11. I can repro with this simple class:
```java
@Parcel
public class MyModel<T> {
    Set<Long> someLongs;
}
```
